In [2]:
subject_ids = os.listdir('/home/jeanettenischan/Data/data_INTENS_TMS/data')


In [3]:
testdata = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/001/pre1/IO_ipsilesional.mat')

NameError: name 'loadmat' is not defined

In [ ]:
testdata.keys()

dict_keys(['__header__', '__version__', '__globals__', 'channel_label', 'localite_timestamps', 'localite_timeseries', 'BrainVisionRDA_stamps', 'BrainVisionRDA_series', 'tms_artifact', 'spongebob_timeseries', 'spongebob_timestamps'])

In [ ]:
testdata(channels)

TypeError: 'dict' object is not callable

In [ ]:
testdata.values

<function dict.values>

In [ ]:
testdata.values()


dict_values([b'MATLAB 5.0 MAT-file Platform: nt, Created on: Fri Mar 25 15:50:20 2022', '1.0', [], array(['Fp1  ', 'Fp2  ', 'F3   ', 'F4   ', 'C3   ', 'C4   ', 'P3   ',
       'P4   ', 'O1   ', 'O2   ', 'F7   ', 'F8   ', 'T7   ', 'T8   ',
       'P7   ', 'P8   ', 'Fz   ', 'Cz   ', 'Pz   ', 'Iz   ', 'FC1  ',
       'FC2  ', 'CP1  ', 'CP2  ', 'FC5  ', 'FC6  ', 'CP5  ', 'CP6  ',
       'FT9  ', 'FT10 ', 'TP9  ', 'TP10 ', 'F1   ', 'F2   ', 'C1   ',
       'C2   ', 'P1   ', 'P2   ', 'AF3  ', 'AF4  ', 'FC3  ', 'FC4  ',
       'CP3  ', 'CP4  ', 'PO3  ', 'PO4  ', 'F5   ', 'F6   ', 'C5   ',
       'C6   ', 'P5   ', 'P6   ', 'AF7  ', 'AF8  ', 'FT7  ', 'FT8  ',
       'TP7  ', 'TP8  ', 'PO7  ', 'PO8  ', 'Fpz  ', 'CPz  ', 'POz  ',
       'Oz   ', 'EDC_L', 'ECR_L', 'FCR_L', 'TB_L ', 'EDC_R', 'ECR_R',
       'FCR_R', 'TB_R ', 'FDS_L', 'FDS_R', 'BB_L ', 'BB_R '], dtype='<U5'), array([[95113.47727691, 95116.97458483, 95124.72665519, 95128.70897458,
        95306.46071261, 95310.41694679, 95314.6029064

In [ ]:
testdata.get('BrainVisionRDA_series')

array([[ 63.7,  11.1, 175.1, ...,  44.5,   7.4,  31.4],
       [ 64.4,  15. , 177.6, ...,  44.3,   8.4,  30.8],
       [ 62.7,  19.7, 175.7, ...,  44.7,   9.3,  31.1],
       ...,
       [-26.3, -64.5, 480.7, ...,  25. ,  25.1,  34.3],
       [-27.8, -65.4, 476.2, ...,  27.4,  24.7,  34.1],
       [-26.2, -66.2, 482.1, ...,  36.9,  23.7,  35.7]], dtype=float32)

In [ ]:
testdata

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Fri Mar 25 15:50:20 2022',
 '__version__': '1.0',
 '__globals__': [],
 'channel_label': array(['Fp1  ', 'Fp2  ', 'F3   ', 'F4   ', 'C3   ', 'C4   ', 'P3   ',
        'P4   ', 'O1   ', 'O2   ', 'F7   ', 'F8   ', 'T7   ', 'T8   ',
        'P7   ', 'P8   ', 'Fz   ', 'Cz   ', 'Pz   ', 'Iz   ', 'FC1  ',
        'FC2  ', 'CP1  ', 'CP2  ', 'FC5  ', 'FC6  ', 'CP5  ', 'CP6  ',
        'FT9  ', 'FT10 ', 'TP9  ', 'TP10 ', 'F1   ', 'F2   ', 'C1   ',
        'C2   ', 'P1   ', 'P2   ', 'AF3  ', 'AF4  ', 'FC3  ', 'FC4  ',
        'CP3  ', 'CP4  ', 'PO3  ', 'PO4  ', 'F5   ', 'F6   ', 'C5   ',
        'C6   ', 'P5   ', 'P6   ', 'AF7  ', 'AF8  ', 'FT7  ', 'FT8  ',
        'TP7  ', 'TP8  ', 'PO7  ', 'PO8  ', 'Fpz  ', 'CPz  ', 'POz  ',
        'Oz   ', 'EDC_L', 'ECR_L', 'FCR_L', 'TB_L ', 'EDC_R', 'ECR_R',
        'FCR_R', 'TB_R ', 'FDS_L', 'FDS_R', 'BB_L ', 'BB_R '], dtype='<U5'),
 'localite_timestamps': array([[95113.47727691, 95116.97458483,

In [ ]:
print(testdata)

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Fri Mar 25 15:50:20 2022', '__version__': '1.0', '__globals__': [], 'channel_label': array(['Fp1  ', 'Fp2  ', 'F3   ', 'F4   ', 'C3   ', 'C4   ', 'P3   ',
       'P4   ', 'O1   ', 'O2   ', 'F7   ', 'F8   ', 'T7   ', 'T8   ',
       'P7   ', 'P8   ', 'Fz   ', 'Cz   ', 'Pz   ', 'Iz   ', 'FC1  ',
       'FC2  ', 'CP1  ', 'CP2  ', 'FC5  ', 'FC6  ', 'CP5  ', 'CP6  ',
       'FT9  ', 'FT10 ', 'TP9  ', 'TP10 ', 'F1   ', 'F2   ', 'C1   ',
       'C2   ', 'P1   ', 'P2   ', 'AF3  ', 'AF4  ', 'FC3  ', 'FC4  ',
       'CP3  ', 'CP4  ', 'PO3  ', 'PO4  ', 'F5   ', 'F6   ', 'C5   ',
       'C6   ', 'P5   ', 'P6   ', 'AF7  ', 'AF8  ', 'FT7  ', 'FT8  ',
       'TP7  ', 'TP8  ', 'PO7  ', 'PO8  ', 'Fpz  ', 'CPz  ', 'POz  ',
       'Oz   ', 'EDC_L', 'ECR_L', 'FCR_L', 'TB_L ', 'EDC_R', 'ECR_R',
       'FCR_R', 'TB_R ', 'FDS_L', 'FDS_R', 'BB_L ', 'BB_R '], dtype='<U5'), 'localite_timestamps': array([[95113.47727691, 95116.97458483, 95124.7266551

In [ ]:
testdata['localite timestamps']

KeyError: 'localite timestamps'

In [ ]:
testdata['localite_timestamps']

array([[95113.47727691, 95116.97458483, 95124.72665519, 95128.70897458,
        95306.46071261, 95310.41694679, 95314.60290641, 95318.91838653,
        95323.32558814, 95327.55789303, 95331.76316414, 95335.51942911,
        95339.76876027, 95343.88091214, 95348.23617715, 95352.1124207 ,
        95356.21666393, 95360.27193603, 95364.74821796, 95369.01338109,
        95373.04666191, 95381.39113163, 95395.6219886 , 95399.46921696,
        95403.39844774, 95407.90173681, 95411.64195546, 95415.25406466,
        95419.05638579, 95422.66159157, 95426.92751211, 95430.97411986,
        95435.29650068, 95439.59464323, 95443.27892179, 95447.05907618,
        95451.09437119, 95455.23275232, 95464.27611163, 95472.14127762,
        95485.94837193, 95490.16760861, 95494.14295392, 95497.79111009,
        95501.90232739, 95505.97053117, 95509.77573313, 95513.43200922,
        95517.48924261, 95525.2696926 , 95529.58274654, 95533.78225291,
        95537.40749961, 95541.70671223, 95546.05092562, 95550.08

In [ ]:
testdata['localite_timestamps'][0]

array([95113.47727691, 95116.97458483, 95124.72665519, 95128.70897458,
       95306.46071261, 95310.41694679, 95314.60290641, 95318.91838653,
       95323.32558814, 95327.55789303, 95331.76316414, 95335.51942911,
       95339.76876027, 95343.88091214, 95348.23617715, 95352.1124207 ,
       95356.21666393, 95360.27193603, 95364.74821796, 95369.01338109,
       95373.04666191, 95381.39113163, 95395.6219886 , 95399.46921696,
       95403.39844774, 95407.90173681, 95411.64195546, 95415.25406466,
       95419.05638579, 95422.66159157, 95426.92751211, 95430.97411986,
       95435.29650068, 95439.59464323, 95443.27892179, 95447.05907618,
       95451.09437119, 95455.23275232, 95464.27611163, 95472.14127762,
       95485.94837193, 95490.16760861, 95494.14295392, 95497.79111009,
       95501.90232739, 95505.97053117, 95509.77573313, 95513.43200922,
       95517.48924261, 95525.2696926 , 95529.58274654, 95533.78225291,
       95537.40749961, 95541.70671223, 95546.05092562, 95550.08819079,
      

In [ ]:
testdata['localite_timestamps'][0][0]

95113.47727691088

In [ ]:
testdata['localite_timestamps'].size()

TypeError: 'int' object is not callable

In [ ]:
testdata['localite_timestamps'].shape

(1, 178)

In [ ]:
testdata['localite_timestamps'].size

SyntaxError: EOL while scanning string literal (<ipython-input-49-a2a18bf1d96b>, line 1)

In [ ]:
testdata['localite_timestamps'].size

178

In [ ]:
testdata.keys

<function dict.keys>

In [ ]:
testdata.keys()

dict_keys(['__header__', '__version__', '__globals__', 'channel_label', 'localite_timestamps', 'localite_timeseries', 'BrainVisionRDA_stamps', 'BrainVisionRDA_series', 'tms_artifact', 'spongebob_timeseries', 'spongebob_timestamps'])

In [ ]:
testdata['BrainVisionRDA_series'].shape

(1253670, 76)

In [ ]:
testdata['BrainVisionRDA_series'][:][64]

array([  62.5,   30.9,  174. ,   61.8,  147.7,  225.4,   64. ,    1. ,
         47.2,   39.5,   63.2,   57. ,    2.9,   14.1,   15. ,  -21.4,
         46.1,   96.6,   41.6,  -17. , -494. ,   89.2,   82.5,   80. ,
        124.2,   59.1,  246.1,  -19. ,   25.6,    2.3,  102.2,  -24. ,
         87.7,  115.4,  154. ,  -33. ,  159.9,  167.3,   95.1,  102.9,
         71.3,   97.3,  115.2,   19.2,  188.8,   54.5, -390.9,   96.9,
        217.9,   48.4,   29.7,   67.2,   42.8,   66.4,  102.3,   68.7,
         51.2,   25.8,  112.3,   55. ,   88. ,   54.9,   77.4,   87.5,
          2.4,    5.3,   29.5,  -96.9,   10.3,    1.3,   41.7,   11.7,
        -12.1,   44.4,    8.7,   31.7], dtype=float32)

In [ ]:
testdata['BrainVisionRDA_series'][:][64].size

76

In [ ]:
testdata['BrainVisionRDA_series'][64][:]

array([  62.5,   30.9,  174. ,   61.8,  147.7,  225.4,   64. ,    1. ,
         47.2,   39.5,   63.2,   57. ,    2.9,   14.1,   15. ,  -21.4,
         46.1,   96.6,   41.6,  -17. , -494. ,   89.2,   82.5,   80. ,
        124.2,   59.1,  246.1,  -19. ,   25.6,    2.3,  102.2,  -24. ,
         87.7,  115.4,  154. ,  -33. ,  159.9,  167.3,   95.1,  102.9,
         71.3,   97.3,  115.2,   19.2,  188.8,   54.5, -390.9,   96.9,
        217.9,   48.4,   29.7,   67.2,   42.8,   66.4,  102.3,   68.7,
         51.2,   25.8,  112.3,   55. ,   88. ,   54.9,   77.4,   87.5,
          2.4,    5.3,   29.5,  -96.9,   10.3,    1.3,   41.7,   11.7,
        -12.1,   44.4,    8.7,   31.7], dtype=float32)

In [ ]:
testdata['BrainVisionRDA_series'][:,64].size

1253670

In [ ]:
testdata['BrainVisionRDA_series'][:,64]

array([ 3.9,  4. ,  5.5, ..., -4.5, -3.2, -5. ], dtype=float32)

In [ ]:
channel = 'EDC'

In [ ]:
chan = channel+'_L'

In [ ]:
testdata['channel_label'].index(chan)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
testdata['channel_label'].index('EDC_L')

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
testdata['channel_label'].shape


(76,)

In [ ]:
testdata['channel_label'][:,1].index(chan)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
testdata['channel_label'].index(chan)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
index = np.where(testdata['channel_label']==chan)

NameError: name 'np' is not defined

In [ ]:
import numpy as np

In [ ]:
index = np.where(testdata['channel_label']==chan)

In [ ]:
print(index)

(array([64]),)


In [ ]:
index = np.where(testdata['channel_label']== 'EDC_L')

In [ ]:
index, = np.where(testdata['channel_label']== 'EDC_L')

In [ ]:
index, = np.where(testdata['channel_label']== chan)

In [ ]:
testdata['channel_label']

array(['Fp1  ', 'Fp2  ', 'F3   ', 'F4   ', 'C3   ', 'C4   ', 'P3   ',
       'P4   ', 'O1   ', 'O2   ', 'F7   ', 'F8   ', 'T7   ', 'T8   ',
       'P7   ', 'P8   ', 'Fz   ', 'Cz   ', 'Pz   ', 'Iz   ', 'FC1  ',
       'FC2  ', 'CP1  ', 'CP2  ', 'FC5  ', 'FC6  ', 'CP5  ', 'CP6  ',
       'FT9  ', 'FT10 ', 'TP9  ', 'TP10 ', 'F1   ', 'F2   ', 'C1   ',
       'C2   ', 'P1   ', 'P2   ', 'AF3  ', 'AF4  ', 'FC3  ', 'FC4  ',
       'CP3  ', 'CP4  ', 'PO3  ', 'PO4  ', 'F5   ', 'F6   ', 'C5   ',
       'C6   ', 'P5   ', 'P6   ', 'AF7  ', 'AF8  ', 'FT7  ', 'FT8  ',
       'TP7  ', 'TP8  ', 'PO7  ', 'PO8  ', 'Fpz  ', 'CPz  ', 'POz  ',
       'Oz   ', 'EDC_L', 'ECR_L', 'FCR_L', 'TB_L ', 'EDC_R', 'ECR_R',
       'FCR_R', 'TB_R ', 'FDS_L', 'FDS_R', 'BB_L ', 'BB_R '], dtype='<U5')

In [ ]:
testdata['channel_label']=='F3'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [ ]:
chan


'EDC_L'

In [ ]:
testdata['channel_label']==chan

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False])

In [ ]:
np.where(testdata['channel_label']== chan)

(array([64]),)

In [ ]:
print(np.where(testdata['channel_label']== chan))

(array([64]),)


In [ ]:
x = np.where(testdata['channel_label']== chan)

In [ ]:
print(x)


(array([64]),)


In [ ]:
np.where(testdata['channel_label']== chan)[0]

array([64])

In [ ]:
np.where(testdata['channel_label']== chan)[0,0]

TypeError: tuple indices must be integers or slices, not tuple

In [ ]:
from scipy.io import loadmat
testdata = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/001/pre1/IO_ipsilesional.mat')

In [ ]:
testdata['BrainVisionRDA_series'].shape

(1253670, 76)

In [ ]:
testdata['localite_timeseries'].shape

(178,)

In [ ]:
testdata['tms_artifact'].shape

(1, 178)

In [ ]:
testdata['spongebob_timeseries'].shape


(1249265, 1, 13)

In [ ]:
testdata['localite_timeseries']

array(['{"coil_0_didt": 44.0}                                                                                                                                                                                                                                                                                                                                                                                                                                   ',
       '{"coil_0_didt": 41.0}                                                                                                                                                                                                                                                                                                                                                                                                                                   ',
       '{"coil_0_didt": 41.0}                                                                     

In [ ]:
testdata['tms_artifact'][:,1]

array([8549], dtype=int32)

In [ ]:
dict(testdata['localite_timeseries'].flatten()).values()

ValueError: dictionary update sequence element #0 has length 440; 2 is required

In [ ]:
testdata['localite_timeseries'][0]

'{"coil_0_didt": 44.0}                                                                                                                                                                                                                                                                                                                                                                                                                                   '

In [ ]:
import ast
temp = ast.literal_eval(testdata['localite_timeseries'][0])

In [ ]:
list(temp.values())

[44.0]

In [ ]:
def extract_intens (string_array):
    '''extracts the value of a dictionary that was stored as string
    iterates over an array of dict strings and converts each into actual dict
    then takes the value of the key/value pair in the dict and stores it in list
    Input: string_array (array of dictionary strings)
    Output: intensity
    https://stackoverflow.com/questions/7002429/how-can-i-extract-all-values-from-a-dictionary-in-python
    https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary '''
    intensity = [] # define empty list for intensity values
    for string in string_array:
        temp = ast.literal_eval(string_array[string]) # convert string into dict
        intensity[string] = list(temp.values()) # extract value from dict and store in list
        return intensity
        

In [ ]:
extract_intens(testdata['localite_timeseries'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
len(testdata['localite_timeseries'])

178

In [ ]:
def extract_intens (string_array):
    '''extracts the value of a dictionary that was stored as string
    iterates over an array of dict strings and converts each into actual dict
    then takes the value of the key/value pair in the dict and stores it in list
    Input: string_array (array of dictionary strings)
    Output: intensity
    https://stackoverflow.com/questions/7002429/how-can-i-extract-all-values-from-a-dictionary-in-python
    https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary '''
    intensity = [] # define empty list for intensity values
    for i in len(string_array):
        temp = ast.literal_eval(string_array[i]) # convert string into dict
        intensity[i] = list(temp.values()) # extract value from dict and store in list
        return intensity

In [ ]:
extract_intens(testdata['localite_timeseries'])

TypeError: 'int' object is not iterable

In [ ]:
def extract_intens (string_array):
    '''extracts the value of a dictionary that was stored as string
    iterates over an array of dict strings and converts each into actual dict
    then takes the value of the key/value pair in the dict and stores it in list
    Input: string_array (array of dictionary strings)
    Output: intensity
    https://stackoverflow.com/questions/7002429/how-can-i-extract-all-values-from-a-dictionary-in-python
    https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary '''
    intensity = [] # define empty list for intensity values
    for i in range(0,len(string_array)):
        temp = ast.literal_eval(string_array[i]) # convert string into dict
        intensity[i] = list(temp.values()) # extract value from dict and store in list
        return intensity

In [ ]:
extract_intens(testdata['localite_timeseries'])

IndexError: list assignment index out of range

In [ ]:
def extract_intens (string_array):
    '''extracts the value of a dictionary that was stored as string
    iterates over an array of dict strings and converts each into actual dict
    then takes the value of the key/value pair in the dict and stores it in list
    Input: string_array (array of dictionary strings)
    Output: intensity
    https://stackoverflow.com/questions/7002429/how-can-i-extract-all-values-from-a-dictionary-in-python
    https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary '''
    intensity = [] # define empty list for intensity values
    for i in range(0,len(string_array)):
        temp = ast.literal_eval(string_array[i]) # convert string into dict
        intensity.append = list(temp.values()) # extract value from dict and store in list
        return intensity

In [ ]:
extract_intens(testdata['localite_timeseries'])

AttributeError: 'list' object attribute 'append' is read-only

In [ ]:
def extract_intens (string_array):
    '''extracts the value of a dictionary that was stored as string
    iterates over an array of dict strings and converts each into actual dict
    then takes the value of the key/value pair in the dict and stores it in list
    Input: string_array (array of dictionary strings)
    Output: intensity
    https://stackoverflow.com/questions/7002429/how-can-i-extract-all-values-from-a-dictionary-in-python
    https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary '''
    intensity = [] # define empty list for intensity values
    for i in range(0,len(string_array)):
        temp = ast.literal_eval(string_array[i]) # convert string into dict
        intensity.append(list(temp.values())[0]) # extract value from dict and store in list
    return intensity

In [ ]:
list(temp.values())[0]

44.0

In [ ]:
extract_intens(testdata['localite_timeseries'])

[44.0,
 41.0,
 41.0,
 39.0,
 52.0,
 48.0,
 66.0,
 35.0,
 54.0,
 44.0,
 44.0,
 62.0,
 56.0,
 66.0,
 62.0,
 41.0,
 48.0,
 66.0,
 62.0,
 62.0,
 58.0,
 66.0,
 48.0,
 48.0,
 35.0,
 41.0,
 32.0,
 31.0,
 54.0,
 66.0,
 58.0,
 62.0,
 35.0,
 45.0,
 32.0,
 66.0,
 56.0,
 61.0,
 37.0,
 44.0,
 44.0,
 48.0,
 32.0,
 41.0,
 35.0,
 31.0,
 32.0,
 35.0,
 41.0,
 62.0,
 41.0,
 66.0,
 58.0,
 52.0,
 44.0,
 31.0,
 32.0,
 61.0,
 35.0,
 39.0,
 62.0,
 54.0,
 56.0,
 44.0,
 49.0,
 61.0,
 32.0,
 37.0,
 41.0,
 44.0,
 48.0,
 66.0,
 32.0,
 54.0,
 54.0,
 66.0,
 56.0,
 35.0,
 62.0,
 56.0,
 44.0,
 54.0,
 41.0,
 52.0,
 58.0,
 39.0,
 48.0,
 37.0,
 37.0,
 62.0,
 66.0,
 66.0,
 58.0,
 54.0,
 48.0,
 35.0,
 44.0,
 35.0,
 58.0,
 31.0,
 48.0,
 66.0,
 39.0,
 56.0,
 61.0,
 66.0,
 44.0,
 41.0,
 31.0,
 37.0,
 52.0,
 39.0,
 44.0,
 58.0,
 66.0,
 62.0,
 58.0,
 62.0,
 54.0,
 58.0,
 44.0,
 49.0,
 48.0,
 52.0,
 37.0,
 32.0,
 39.0,
 66.0,
 62.0,
 62.0,
 52.0,
 31.0,
 37.0,
 52.0,
 58.0,
 31.0,
 66.0,
 58.0,
 35.0,
 37.0,
 49.0,
 39.0,
 54.0,

In [ ]:
list(testdata['tms_artifact'][0])

[5049,
 8549,
 16304,
 20285,
 198032,
 201996,
 206174,
 210486,
 214892,
 219132,
 223336,
 227089,
 231336,
 235454,
 239811,
 243687,
 247787,
 251842,
 256309,
 260584,
 264618,
 272963,
 287189,
 291041,
 294971,
 299470,
 303203,
 306824,
 310624,
 314232,
 318494,
 322544,
 326868,
 331167,
 334846,
 338628,
 342663,
 346799,
 355848,
 363706,
 377517,
 381736,
 385711,
 389359,
 393472,
 397538,
 401336,
 405002,
 409061,
 416842,
 421141,
 425343,
 428963,
 433276,
 437611,
 441656,
 446013,
 449893,
 453539,
 467575,
 471332,
 474941,
 478859,
 482705,
 486647,
 490772,
 494371,
 498249,
 501873,
 506189,
 509989,
 514229,
 518032,
 522288,
 526136,
 534582,
 538750,
 542994,
 557271,
 561234,
 565002,
 569288,
 573161,
 577712,
 581711,
 585252,
 588986,
 597889,
 713927,
 718265,
 722801,
 726858,
 731278,
 735057,
 739536,
 743333,
 747371,
 751891,
 755810,
 760129,
 764363,
 768766,
 772464,
 776923,
 781100,
 784798,
 788457,
 802059,
 806237,
 810758,
 815273,
 818998

In [ ]:
testdata['spongebob_timeseries'][:,:,11]

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
testdata

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Fri Mar 25 15:50:20 2022',
 '__version__': '1.0',
 '__globals__': [],
 'channel_label': array(['Fp1  ', 'Fp2  ', 'F3   ', 'F4   ', 'C3   ', 'C4   ', 'P3   ',
        'P4   ', 'O1   ', 'O2   ', 'F7   ', 'F8   ', 'T7   ', 'T8   ',
        'P7   ', 'P8   ', 'Fz   ', 'Cz   ', 'Pz   ', 'Iz   ', 'FC1  ',
        'FC2  ', 'CP1  ', 'CP2  ', 'FC5  ', 'FC6  ', 'CP5  ', 'CP6  ',
        'FT9  ', 'FT10 ', 'TP9  ', 'TP10 ', 'F1   ', 'F2   ', 'C1   ',
        'C2   ', 'P1   ', 'P2   ', 'AF3  ', 'AF4  ', 'FC3  ', 'FC4  ',
        'CP3  ', 'CP4  ', 'PO3  ', 'PO4  ', 'F5   ', 'F6   ', 'C5   ',
        'C6   ', 'P5   ', 'P6   ', 'AF7  ', 'AF8  ', 'FT7  ', 'FT8  ',
        'TP7  ', 'TP8  ', 'PO7  ', 'PO8  ', 'Fpz  ', 'CPz  ', 'POz  ',
        'Oz   ', 'EDC_L', 'ECR_L', 'FCR_L', 'TB_L ', 'EDC_R', 'ECR_R',
        'FCR_R', 'TB_R ', 'FDS_L', 'FDS_R', 'BB_L ', 'BB_R '], dtype='<U5'),
 'localite_timestamps': array([[95113.47727691, 95116.97458483,

In [ ]:
testdata['localite_timeseries']

array(['{"coil_0_didt": 44.0}                                                                                                                                                                                                                                                                                                                                                                                                                                   ',
       '{"coil_0_didt": 41.0}                                                                                                                                                                                                                                                                                                                                                                                                                                   ',
       '{"coil_0_didt": 41.0}                                                                     

In [ ]:
#file_array = []
if file_array:
    print('There is a list')
if not file_array:
    print('list is empty')    

list is empty


In [ ]:
if '_180_' in xdf_files[1]:
    print('180')
elif '_0_' in xdf_files[1]:
    print('0')    


0


In [ ]:
if os.listdir(direct + '/009/post5/'):
    print('Folder contains files')

In [ ]:
import liesl
from liesl.api import XDFFile
xdf_file = XDFFile('/home/jeanettenischan/Data/data_INTENS_TMS/data/015/pre1/TMS_ioc_0_ipsilesional_PoHe_pre1.xdf')
print(xdf_file)
print(xdf_file['TMS_Triggermarker IOC'].time_series)


XDFFile: Parsing BrainVision RDA Markers
XDFFile: Parsing BrainVision RDA
XDFFile: Parsing TMS_Triggermarker IOC
XDFFile: Parsing Spongebob-Data
{'BrainVision RDA Markers': XDFStream(name=BrainVision RDA Markers, type=Markers, hostname=TMSPC64, created_at=22135.58698058, chan_count=1, ), 'BrainVision RDA': XDFStream(name=BrainVision RDA, type=EEG, hostname=TMSPC64, created_at=22135.584296781, duration=-0.000999998675979441, chan_count=72, ), 'TMS_Triggermarker IOC': XDFStream(name=TMS_Triggermarker IOC, type=Markers, hostname=Patrick, created_at=278265.746852138, duration=-5.945789867750136, chan_count=4, ), 'Spongebob-Data': XDFStream(name=Spongebob-Data, type=EEG, hostname=Patrick, created_at=266743.644142465, duration=-0.0010049247975985054, chan_count=13, )}
[['TMS_Trigger', '0', '54.0', '100'], ['TMS_Trigger', '0', '54.0', '100'], ['TMS_Trigger', '0', '54.0', '100'], ['TMS_Trigger', '0', '54.0', '100'], ['TMS_Trigger', '0', '54.0', '100'], ['TMS_Trigger', '0', '54.0', '100'], ['TM

In [17]:
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
import glob
from scipy import stats
import pandas as pd
import itertools
from scipy import io
import scipy
import keyboard
import math
from scipy.io import loadmat

testdataset_0 = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/015/pre1/IO_ipsilesional_0.mat')
hem0 = testdataset_0.keys()
print(hem0)
testdataset_180 = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/015/pre1/IO_ipsilesional_180.mat')
hem180 = testdataset_180.keys()
print(hem180)

a = testdataset_180['tms_artifact']
b = testdataset_0['tms_artifact']
print(a)
print('Next')
print(b)#print(testdataset['phases'])

dict_keys(['__header__', '__version__', '__globals__', 'channel_label', 'BrainVisionRDA_stamps', 'BrainVisionRDA_series', 'tms_artifact', 'spongebob_timeseries', 'spongebob_timestamps'])
dict_keys(['__header__', '__version__', '__globals__', 'channel_label', 'BrainVisionRDA_stamps', 'BrainVisionRDA_series', 'tms_artifact', 'spongebob_timeseries', 'spongebob_timestamps'])
[[ 41579  46277  50838  56623  61228  65785  71306  77059  82354  86619
  103508 109325 114623 119898 124724 129818 135780 140496 144742 149778
  166918 171699 177437 181838 187161 191764 196847 202009 208013 213316
  230791 236597 241861 246624 251068 255372 261078 266901 272161 278066
  294588 298813 303056 307664 311708 317392 322318 326820 331740 337330
  354103 358648 363092 367198 372604 376885 381690 385913 390057 396041
  418940 424565 428909 434432 438880 443722 449105 453510 459438 465360
  484551 489478 494420 499103 504089 508568 514197 519297 525009 529933
  556108 561425 565561 571419 575764 581147 585542

In [29]:
test_IO = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/015/pre1/IO_ipsilesional.mat')
test_IO['tms_artifact'][0]

array([142407, 146827, 152388, 157090, 162461, 167621, 172514, 178418,
       182697, 186710, 213547, 219417, 225265, 225265, 230617, 236524,
       242303, 247902, 253321, 258784, 264158, 282189, 287593, 292147,
       297151, 302263, 308217, 313841, 317988, 322115, 326351, 372322,
       376382, 381959, 386598, 392297, 396596, 401337, 405740, 410121,
       415879, 435379, 440638, 446374, 451039, 456700, 462237, 466935,
       471191, 476313, 481794, 517284, 521260, 526999, 532675, 537220,
       541956, 547223, 551925, 555923, 561447, 596831, 602032, 607310,
       612829, 617469, 623193, 627735, 632831, 638489, 643408, 661253,
       667107, 671228, 675370, 681247, 687190, 692848, 696866, 701892,
       707824, 726146, 730708, 736659, 742597, 751638, 756261, 761501,
       765558, 769907])

In [44]:
test_subkey = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/015/post3/IO_ipsilesional.mat')
if 'localite_timeseries' in test_subkey:
    print('stimulation intensity info present')
else:
    print('stimulation intensity not present')  

#print(test_subkey['localite_timeseries'])

FileNotFoundError: [Errno 2] No such file or directory: '/home/jeanettenischan/Data/data_INTENS_TMS/data/015/post3/IO_ipsilesional.mat'

In [107]:
import ast
file = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/008/post5/IO_ipsilesional.mat')
string_array = file['localite_timeseries'].flatten()
string_array.flatten()
print(string_array)

#temp = ast.literal_eval(string_array[5][0])
#print(temp)

['{"coil_0_didt": 62.0}                                                                                                                                                                                                                                                                                                                                                                                                                                            '
 '{"coil_0_didt": 56.0}                                                                                                                                                                                                                                                                                                                                                                                                                                            '
 '{"coil_0_didt": 96.0}                                                                       

In [111]:
import ast
import json
file = loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/015/pre3/IO_ipsilesional.mat')
#print(json.loads(file['localite_timeseries'][0])['coil_0_didt'])
print(file['localite_timeseries'])

[['{"coil_0_didt": 76.0} ']
 ['{"coil_0_didt": 93.0} ']
 ['{"coil_0_didt": 131.0}']
 ['{"coil_0_didt": 76.0} ']
 ['{"coil_0_didt": 86.0} ']
 ['{"coil_0_didt": 103.0}']
 ['{"coil_0_didt": 103.0}']
 ['{"coil_0_didt": 86.0} ']
 ['{"coil_0_didt": 93.0} ']
 ['{"coil_0_didt": 130.0}']
 ['{"coil_0_didt": 131.0}']
 ['{"coil_0_didt": 131.0}']
 ['{"coil_0_didt": 113.0}']
 ['{"coil_0_didt": 69.0} ']
 ['{"coil_0_didt": 103.0}']
 ['{"coil_0_didt": 93.0} ']
 ['{"coil_0_didt": 139.0}']
 ['{"coil_0_didt": 121.0}']
 ['{"coil_0_didt": 86.0} ']
 ['{"coil_0_didt": 131.0}']
 ['{"coil_0_didt": 69.0} ']
 ['{"coil_0_didt": 86.0} ']
 ['{"coil_0_didt": 69.0} ']
 ['{"coil_0_didt": 113.0}']
 ['{"coil_0_didt": 130.0}']
 ['{"coil_0_didt": 68.0} ']
 ['{"coil_0_didt": 121.0}']
 ['{"coil_0_didt": 139.0}']
 ['{"coil_0_didt": 103.0}']
 ['{"coil_0_didt": 86.0} ']
 ['{"coil_0_didt": 111.0}']
 ['{"coil_0_didt": 139.0}']
 ['{"coil_0_didt": 139.0}']
 ['{"coil_0_didt": 68.0} ']
 ['{"coil_0_didt": 131.0}']
 ['{"coil_0_didt": 1

In [ ]:
intensity = []
for i in range(0,len(string_array)):
    temp = ast.literal_eval(string_array[i]) # convert string into dict
    intensity.append(temp['coil_0_didt'])

print(intensity)    

In [34]:
re_shape =  loadmat('/home/jeanettenischan/Data/data_INTENS_TMS/data/003/pre3/IO_ipsilesional.mat')
re_shape.keys()
re_shape['BrainVisionRDA_series'] = np.squeeze(re_shape['BrainVisionRDA_series'])
re_shape['BrainVisionRDA_series'].shape

io.savemat('/home/jeanettenischan/Data/data_INTENS_TMS/data/003/pre3/IO_ipsilesional.mat', re_shape) 

In [63]:
direct  = '/home/jeanettenischan/Data/data_INTENS_TMS/data/'
subject_ids = os.listdir(direct)
subject_ids

['009',
 '015',
 '019',
 '017',
 '011',
 '018',
 '001',
 '006',
 '007',
 '005',
 '010',
 '008',
 '014',
 '004',
 '003',
 '016',
 '002',
 '013',
 '012']

In [118]:
stim_intens_miss = {'009': ['pre1', 'post1'], '015': ['pre1_0', 'pre1_180', 'post1'], '017': ['pre1'], '011': ['pre1_0', 'pre1_180', 'post1'], '001': ['post1'], '007': ['pre1'], '014': ['pre1_0', 'pre1_180', 'post1'], '016': ['post1'], '002': ['pre1', 'post1'], '013': ['post5'], '012': ['pre1', 'post1']}
type(stim_intens_miss)
#stim_intens_miss.keys()
import json
with open('/home/jeanettenischan/Data/data_INTENS_TMS/stim_intens_miss.json' , 'w') as outfile:
    json.dump(stim_intens_miss, outfile)

NameError: name 'json_dump' is not defined

In [26]:
import pandas as pd
import numpy as np
subject_dict = pd.read_json('/home/jeanettenischan/Data/data_INTENS_TMS/ProcessedData/013.json').to_dict()
print(subject_dict['post5'].keys())
#print(len(subject_dict['post5']['stim_intens']))
print(subject_dict['post5']['stim_intens'])
if subject_dict['post5']['stim_intens']:
    print('Intensity available')
print(len(subject_dict['post5']['MEP_data']))
print(len(subject_dict['post5']['TMS_pulse']))
print(subject_dict['post5']['TMS_pulse'][-1])


dict_keys(['MEP_data', 'TMS_pulse', 'stim_intens'])
None
933399
180
923341


In [155]:
type(subject_dict['post3']['MEP_data'])

list

In [33]:
time = list(range(-100,101)) 
print(time)

[-100, -99, -98, -97, -96, -95, -94, -93, -92, -91, -90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [36]:
def epoch_data (MEP_data, upper, lower, timepoint):
    '''function to cut continuous data into epochs of predefined length around a marker.
    Needs dictionary with data, upper and lower boundry of epoch in ms and
    timepoint of measurement as input.'''
    epoch = dict() #create empty dict
    i = 1          #set number for epochs
    for artefact in MEP_data[timepoint]['TMS_pulse']: # iterate over marker
        if MEP_data[timepoint]['stim_intens']:
            epoch[i]['intensity'] = MEP_data[timepoint]['stim_intens'][i-1]
        epoch[i]['MEP'] = MEP_data[timepoint]['MEP_data'][artefact + before_stim : artefact + after_stim]
        epoch[i]['Time'] = list(range(-100,101))     
        i += 1 #update epoch number

    return epoch 

In [6]:
import pandas as pd
alias = '015'
timepoint = 'pre1'
i = 1
before_stim = -100   # time where epoch starts, needs to be negative integer or 0
after_stim = 100
Intens = dict()
len(alias)
MEP_data = pd.read_json('/home/jeanettenischan/Data/data_INTENS_TMS/ProcessedData/' 
                               + alias + '.json').to_dict()
timepoints = MEP_data.keys() # get measurement number from dictionary
print(timepoints)
#print(MEP_data['pre1'])
Intens[str(i)]['Intensity'] = MEP_data[timepoint]['stim_intens'][i-1]
print(Intens)
if MEP_data[timepoint]['stim_intens'] is None:
    print(True)


dict_keys(['pre1', 'post1', 'pre3', 'post5'])


TypeError: 'NoneType' object is not subscriptable

In [54]:
import os
from pathlib import Path
direct = '/home/jeanettenischan/Data/data_INTENS_TMS/ProcessedData/'
subject_ids = []
for ID in os.listdir(direct):
    subject_ids.append(Path(direct + ID).stem)
print(subject_ids)    

['018', '004', '001', '007', '013', '008', '012', '005', '010', '016', '014', '015', '003', '002', '017', 'Epochs', '011', '019', '009', '006']


In [4]:
import os
import pandas as pd

direct = '/home/jeanettenischan/Data/data_INTENS_TMS/ProcessedData/Epochs/'
timepoints = os.listdir(direct)

testdata = pd.read_json( direct + 'post1/007.json').to_dict()
#print(testdata.keys())
trial = testdata[4]
#print(trial['Time'].index(15))
after_stim = trial['MEP'][115:]
#print(after_stim)
#min(trial['MEP'][115:])
#print(trial['MEP'].index(min(trial['MEP'][115:])))
#type(trial['MEP'])
trial.keys()
print(trial['intensity'])

54.0
